apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-postgres-deploy
  template:
    metadata:
      labels:
        app: micro-postgres-deploy
    spec:
      containers:
        - name: postgres
          image: bbiegajlo/micro-postgres:1.3.0
          env:
            - name: POSTGRES_DB
              value: "micropostgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 5432
          # todo - is this necessary (volumes)?
#          volumeMounts:
#            - mountPath: /docker-entrypoint-initdb.d
#              name: init-db
#      volumes:
#        - name: init-db
#          configMap:
#            name: db-init-scripts

---

apiVersion: v1
kind: Service
metadata:
  name: micro-postgres-service
spec:
  selector:
    app: micro-postgres-deploy
  ports:
    - protocol: TCP
      port: 5432  # Default PostgreSQL port